version: '3'

services:
  altapi:
    image: ghcr.io/pjatk21/altapi:main
    ports:
      - 4000:4000
    environment:
      MONGO_URL: 'mongodb://database/altiapi'
    restart: unless-stopped
    depends_on:
      - database
  # Scrappers, a lot of them
  scrapper-zimmer:
    image: ghcr.io/pjatk21/alt-scrap:main
    restart: unless-stopped
    environment:
      SCRAPPER_NAME: Zimmer
      ALTAPI_GATEWAY: ws://altapi:4010/
    depends_on:
      - altapi
  scrapper-benia:
    image: ghcr.io/pjatk21/alt-scrap:main
    restart: unless-stopped
    environment:
      SCRAPPER_NAME: Benia
      ALTAPI_GATEWAY: ws://altapi:4010/
    depends_on:
      - altapi
  # Other useful containers
  database:
    image: mongo:latest
    restart: unless-stopped
