version: '3'

services:
  altapi:
    image: ghcr.io/pjatk21/altapi:main
    ports:
      - 4000:4000
    environment:
      MONGO_URL: 'mongodb://database/altiapi'
    restart: unless-stopped
    depends_on:
      - database
  scrapper:
    image: ghcr.io/pjatk21/alt-scrap:main
    restart: unless-stopped
    environment:
      SCRAPPER_NAME: parseInt('f*ck', 16)
      ALTAPI_GATEWAY: ws://altapi:4010/
    depends_on:
      - altapi
    entrypoint: yarn docker.entrypoint.stealer --delayPerEntry 700
  # Other useful containers
  database:
    image: mongo:latest
    restart: unless-stopped
