version: '3'

services:
  altapi:
    build: .
    image: kpostekk/altapi
    ports:
      - 4000:4000
    environment:
      MONGO_URL: 'mongodb://database/altiapi'
      ALTAPI_UPLOAD_KEY: 'changeMeLater'
    restart: unless-stopped
    depends_on:
      - database
  scrapper:
    image: alt-scrap
    restart: unless-stopped
    cap_add:
      - "SYS_ADMIN"
    environment:
      ALTAPI_URL: 'http://altapi:4000/'
      ALTAPI_UPLOAD_KEY: 'changeMeLater'
  database:
    image: mongo:latest
    restart: unless-stopped
